apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
      - name: spa
        image: a7ryan/spa:1.8
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
        env:
        - name: NAME
          value: "Aadi.7"

---

apiVersion: v1
kind: Service
metadata:
  name: spa-service
spec:
  selector:
    app: spa
  ports:
  - port: 1234
    targetPort: 3000


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spa-ingress
  labels:
    name: spa-ingress
spec:
  rules:
  - host: gateway.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: spa-service
            port: 
              number: 1234
