apiVersion: v1
kind: Pod
metadata:
  name: log-output
  labels:
    name: log-output
spec:
  containers:
  - name: log-output
    image: a7ryan/log_output:latest
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
